#!/usr/bin/python

import os

def graphConnected(filename, n):
	file = open(filename)
	line = file.readline()
	arr = line.split()
	print filename + ": " + arr[0]
	if (int(arr[0]) == n):
		return 1
	else:
		return 0

n = 100
m = 500
sample = 100
event = 0
for i in range(1, sample):
	randfile = "output/rand-" + str(n) + "-" + str(m) + "-" + str(sample)
	os.system("./randomgraph " + str(n) + " " + str(m) + " " + randfile)
	sccfile = "output/scc-" + str(n) + "-" + str(m) + "-" + str(sample)
	os.system("./sccfinder " + randfile + " " + sccfile)
	if (graphConnected(sccfile, n)):
		event += 1
prob = float(event)/sample
print "Sample: " + str(sample) + ". Event: " + str(event) + ". Prob: " + str(prob)
