#!/usr/bin/python

import os
import time

def writeOut(file, n, m, sample, event):
	prob = float(event)/sample
	output = str(m) + " " + str(prob)
	file.write(output + '\n')
	print output

def graphConnected(filename, n):
	file = open(filename)
	line = file.readline()
	arr = line.split()
	if (int(arr[0]) == n):
		return 1
	else:
		return 0

def getParam(prompt):
	while (1):
		input = raw_input(prompt)
		if (input.isdigit()):
			return int(input)
		print 'n must be a number'

filename = 'keepers/' + raw_input('filename: ')
n = getParam('n: ')
file = open(filename, 'w')
sample = getParam('sample: ')
for m in range(getParam('min m: '), getParam('max m: '), getParam('increment m by: ')):
	print 'processing ' + str(n) + ' nodes and ' + str(m) + ' edges.'
	event = 0
	for i in range(1, sample):
		randfile = 'randomfiles/' + str(n) + '-' + str(m) + '-' + str(sample)
		os.system('./randomSCC ' + str(n) + ' ' + str(m) + ' ' + randfile)
		if (graphConnected(randfile, n)):
			event += 1
	writeOut(file, n, m, sample, event)
file.close()
