#!/usr/bin/python

import os
import time

def writeOut(file, n, m, sample, event):
	prob = float(event)/sample
	output = 'n: ' + str(n) + '. m: ' + str(m) + '. Prob: ' + str(prob)
	file.write(output + '\n')
	print 'event: ' + str(event) + '. sample: ' + str(sample)
	print output

def graphConnected(filename, n):
	file = open(filename)
	line = file.readline()
	print line
	arr = line.split()
	if (int(arr[0]) == n):
		return 1
	else:
		return 0

def getParam(prompt):
	while (1):
		input = raw_input(prompt)
		if (input.isdigit()):
			return int(input)
		print 'n must be a number'

n = getParam('n: ')
filename = 'keepers/part2-' + str(n) + '-' + str(time.time())
file = open(filename, 'w')
for m in range(n, getParam('max m: '), getParam('increment m by: ')):
	print 'processing ' + str(n) + ' nodes and ' + str(m) + ' edges.'
	sample = getParam('sample: ')
	event = 0
	for i in range(1, sample):
		print 'pass ' + str(i)
		randfile = 'output/rand-' + str(n) + '-' + str(m) + '-' + str(sample)
		os.system('./randomgraph ' + str(n) + ' ' + str(m) + ' ' + randfile)
		sccfile = 'output/scc-' + str(n) + '-' + str(m) + '-' + str(sample)
		os.system('./sccfinder ' + randfile + ' ' + sccfile)
		if (graphConnected(sccfile, n)):
			event += 1
	writeOut(file, n, m, sample, event)
file.close()
